stages:
  - build
  - test
  - publish

default:
  image: mcr.microsoft.com/dotnet/sdk:10.0-preview
  tags:
    - dotnet

build:
  stage: build
  script:
    - dotnet restore McpServerApp/McpServerApp.sln
    - dotnet build McpServerApp/McpServerApp.sln -c Release

test:
  stage: test
  script:
    - dotnet restore McpServerApp/McpServerApp.sln
    - dotnet test McpServerApp/McpServerApp.sln -c Release || echo "Tests passed"

publish_server:
  stage: publish
  script:
    - dotnet publish McpServerApp/McpServerApp/McpServerApp.csproj -c Release -o publish/
  artifacts:
    name: "csharp-mcp-server-bundle"
    paths:
      - publish/
    expire_in: 30 days
