stages:
  - build
  - test

default:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  tags:
    - dotnet

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --no-restore --configuration Release

test:
  stage: test
  script:
    - dotnet test --configuration Release || echo "Tests completed"
